version: '3.8'

services:
  db:
    image: postgres:17.6
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: doitnow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d doitnow"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

